import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Next.js Tutorial - Learn Next.js",
    template: "%s - Generated by create next app", //%s is replaced by the actual page title
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header
          style={{
            backgroundColor: "lightgreen",
            padding: "10px",
            color: "white",
          }}
        >
          <Header />
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "lightblue",
            padding: "10px",
            color: "white",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
